# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - stocksdata

on:
  push:
    branches:
      - main # Your Azure Function App is configured to deploy from 'main'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12' # Azure Functions supports Python 3.12

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # --- CRITICAL FIX: Ensure host.json is present and zipped from the repo root ---
      # This command explicitly zips the 'stocksdata' folder, 'requirements.txt',
      # AND 'host.json' (which is absolutely necessary for Python Functions).
      - name: Zip artifact for deployment
        run: |
          # IMPORTANT: Confirm 'host.json' exists at the root of your local repository (STOCKSDATAA folder)
          # alongside 'stocksdata' directory and 'requirements.txt'.
          # If it does NOT exist locally, you need to create a basic one there first.
          zip -r release.zip stocksdata requirements.txt host.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip # Upload only the specific zip file created

  deploy:
    runs-on: ubuntu-latest
    needs: build # Ensures the build job completes successfully before deployment starts
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: . # Download the artifact (release.zip) to the current directory
        
      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'stocksdata' # Your Function App name
          slot-name: 'Production'
          package: 'release.zip' # Deploy the specific zip file directly
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BBF2DB12F4B248C4B07678EFD2245F63 }}
